### ISSUE TITLE
use instructions in readme

### ISSUE THREAD

**Issue by jyaw** [mddub/pancreabble#5]
when you do a -h on the uses for the pancreabble device, you get set_time rather than set_clock options. I used the set_time option successfully. Also, the format_urchin_data option only takes a string or json file for the urchin status in addition to the glucose.json. Perhaps the changes in the code aren't up to date per the content in the readme?

**Comment by mddub** [comment]
Had you already installed Pancreabble before? If so, try again:

```
pip install --user git+git://github.com/mddub/pancreabble.git
```

(assuming you installed with `--user` the first time)

Thanks for catching this. I just added #6 to start properly versioning the package. Without that, if you had it already installed, and had called the above without `--upgrade`, pip would have assumed you have the latest, since the version string had never changed.

**Comment by jyaw** [comment]
Oh Ok, user error then I guess. I had used the previous version, so I guess
I needed to use the --upgrade as you suggested. Thanks for clarifying! Will
give it another try.
