### ISSUE TITLE
No information or example file

### ISSUE THREAD

**Issue by fiberfan** [mddub/pancreabble#8]

**Comment by fiberfan** [comment]
Sorry, stray return.  There is no info or example of what the subject.py and message.py should do.  I haven't been able to find any info after several Google attempts.

**Comment by mddub** [comment]
Yes, sorry, you'll have to write your own code to do that. In that example, `pebble_subject.py` and `pebble_message.py` would be Python scripts which read the loop state from disk and summarize it as subject/message text for the Pebble notification. Since everyone runs their loop slightly differently (different algorithms, different report structure, different patterns of storing/deleting stale loop data) and wants their data summarized differently, it's up to you to decide.

That said, if you're using oref0, the setup script on the dev branch now sets this up for you: https://github.com/openaps/oref0/pull/329

If you want to use that code as a starting point, it's a bash script which pulls data fields from the oref0 reports using `jq`: https://github.com/openaps/oref0/blob/7ad9da7/bin/peb-urchin-status.sh
